### ISSUE TITLE
Babel_disable_cache is not recognized as an internal or external command

### ISSUE THREAD

**Issue by farmasek** [RyanCCollins/scalable-react-boilerplate#36]
Hi, i tried new test setup, bud i couldnt make it work, my guess is its because of windows enviroment variables ? 

i tried uninstall babel, and install babel-cli, but no change.
when i run test it throws this error:

> BABEL_DISABLE_CACHE=1 NODE_ENV=test node --harmony_proxies node_modules/.bin/jest
> 
> 'BABEL_DISABLE_CACHE' is not recognized as an internal or external command,
> operable program or batch file.
> 
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Farmas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> npm ERR! scalable-react-boilerplate@1.1.0 test: `BABEL_DISABLE_CACHE=1 NODE_ENV=test node --harmony_proxies node_modules/.bin/jest`
> npm ERR! Exit status 1

**Comment by RyanCCollins** [comment]
I think it's the same thing as before, the node scripts need to be run with `cross-env` before setting environment variables.

**Comment by RyanCCollins** [comment]
I think my latest commit to master should solve this as shown above.  Thanks for being my Windows guinea pig and sorry for the trouble!

**Comment by farmasek** [comment]
It helped, but it didn't solve the problem completely, now it throws 
scalable-react-boilerplate@1.1.0 test E:\scalable-react-boilerplate
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=test node --harmony_proxies node_modules/.bin/jest

> E:\scalable-react-boilerplate\node_modules\.bin\jest:2
> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
>           ^^^^^^^
> SyntaxError: missing ) after argument list
>     at Object.exports.runInThisContext (vm.js:76:16)
>     at Module._compile (module.js:513:28)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.runMain (module.js:575:10)
>     at run (bootstrap_node.js:352:7)
>     at startup (bootstrap_node.js:144:9)
>     at bootstrap_node.js:467:3

besides your after your last commit  i  got 

> npm ERR! Invalid Package: expected grommet but found grommet-udacity

i had to put the version back.
No problem with testing on Windows for you :)

**Comment by RyanCCollins** [comment]
Do'h!! Sorry that was really sloppy of me!  I am not sure how that got through CI.  Let me fix it now. I ended up having to fork the Grommet library and made my own package, called grommet-udacity.  It has some extra components and stylesheets, so needs to be referenced from grommet-udacity.  This is of course just for the demo and you don't need to use Grommet at all.

**Comment by farmasek** [comment]
Hi, your last push just fixed the grommet error, but the first mentioned remains .
